sudo: required
services:
    - docker

before_install:
    - docker build -t destination/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run destination/react-test npm test -- --coverage

after_success:
    - docker build -t destination/multi-client ./client
    - docker build -t destination/multi-nginx ./nginx
    - docker build -t destination/multi-server ./server
    - docker build -t destination/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to docker hub 
    - docker push destination/multi-client
    - docker push destination/multi-nginx
    - docker push destination/multi-server
    - docker push destination/multi-worker


